routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\VisitorController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('visitorrs', function () {
    return view('visitorrs');
});

Route::get('visitorr', function () {
    return view('visitorr');
});

Route::get('events', function () {
    return view('events');
});

Route::get('history', function () {
    return view('history');
});

Route::get('historyPreRegister', function () {
    return view('historyPreRegister');
});


Route::get('userEdit', function () {
    return view('userEdit');
});

Route::get('qrCode', function () {
    return view('qrCode');
});

Route::get('qr-code-g', function () {


    \QrCode::size(500)

            ->format('png')

            ->generate('HDTuto.com', public_path('images/qrcode.png'));

  return view('qrCode');

});

Route::get('homeAdmin', function () {
    return view('homeAdmin');
});

Route::get('CheckInVisitor', function () {
    return view('CheckInVisitor');
});

Route::get('RegInVisitor', function () {
    return view('RegInVisitor');
});

Route::get('reg_visitor', function () {
    return view('reg_visitor');
});

Route::get('CheckOutVisitor', function () {
    return view('CheckOutVisitor');
});

Route::get('reg_visitors', function () {
    return view('reg_visitors');
});


Route::get('historyAdmin', function () {
    return view('historyAdmin');
});

Route::get('adminProfile', function () {
    return view('adminProfile');
});

Route::resource('visitorrs','VisitorController');
Route::resource('events','EventController');
Route::resource('reg_visitors','RegVisitorController');
Route::resource('users','UserController');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/homes', 'HomeController@index')->name('homes');

Route::get('admin/home', 'HomeController@adminHome')->name('admin.home')->middleware('is_admin');

Route::get('/search2', 'VisitorController@search2')->name('Search2');

Route::get('/historyPreRegister', 'historyPreRegisterController@index')->name('historyPreRegister');

Route::get('/search3', 'EventController@search3')->name('Search3');

Route::get('/search4', 'CheckOutController@search4')->name('Search4');

Route::get('/CheckOutVisitor', 'CheckOutController@index')->name('CheckOutVisitor');

Route::get('/CheckInVisitor', 'CheckInController@index')->name('CheckInVisitor');

Route::get('/search', 'CheckInController@search')->name('CheckInVisitor');

Route::get('/search5', 'HistoryAdminVisitorController@search5')->name('Search5');

Route::get('/search6', 'RegVisitorController@search6')->name('Search6');

Route::get('/historyVisitor', 'HistoryVisitorController@index')->name('historyVisitor');

Route::get('/search7', 'HistoryVisitorController@search7')->name('Search7');

Route::get('/historyEvent', 'HistoryEventController@index')->name('historyEvent');

Route::get('/search8', 'HistoryEventController@search8')->name('Search8');

Route::get('/CheckOut', 'CheckOut2Controller@index2')->name('CheckOut');

Route::get('/search9', 'CheckOut2Controller@search9')->name('Search9');

Route::get('/edit/{id}', 'UserController@edit')->name('Edit');

Route::post('/update/{id}', 'UserController@update')->name('Update');

Route::get('/userEdit', 'UserController@index')->name('userEdit');

Route::get('users/edit2/{id}', 'UserController@edit2')->name('Edit2');

Route::patch('users/update2/{id}', 'UserController@update2')->name('update2');

Route::get('/adminProfile', 'UserController@adminIndex')->name('adminProfile');

Route::get('/changePassword', 'UserController@changePassword')->name('changePassword');

Route::post('users/updatePassword/', 'UserController@updatePassword')->name('updatePassword');

Route::get('/changePassword2', 'UserController@changePassword2')->name('changePassword2');

Route::post('users/updatePassword2/', 'UserController@updatePassword2')->name('updatePassword2');

//Route::get('/CheckInVisitor/edit2/{id}', 'CheckInController@edit2')->name('CheckInVisitor.edit2');

Route::get('active/{id}', 'CheckInController@active')->name('active');
Route::get('inactive/{id}', 'CheckInController@inactive')->name('inactive');

Route::get('active2/{id}', 'CheckOutController@active2')->name('active2');
Route::get('inactive2/{id}', 'CheckOutController@inactive2')->name('inactive2');

Route::get('active4/{id}', 'CheckOut2Controller@active4')->name('active4');
Route::get('inactive4/{id}', 'CheckOut2Controller@inactive4')->name('inactive4');

Route::get('/displayCheckIn/{token}', 'VisitorController@checkin')->name('displayCheckIn');
Route::post('/visitorCheckedIn', 'VisitorController@checkedin')->name('visitorCheckedIn');

Route::get('/displayCheckOut/{token}', 'VisitorController@checkout')->name('displayCheckOut');
Route::post('/visitorCheckedOut', 'VisitorController@checkedout')->name('visitorCheckedOut');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use App\Visitorr;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'is_admin','user_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    public function visitorrs()
    {
      return $this->hasMany (Visitorr::class);

    }

    public function events()
    {
      return $this->hasMany (Event::class);

    }
    public function reg_visitors()
    {
      return $this->hasMany (RegVisitor::class);

    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use Auth;
use Hash;

class UserController extends Controller
{
  public function __construct()
  {
      $this->middleware('auth');
  }
  public function index(Request $request)
  {
    $users= User::with('users')->where('user_id',Auth::user()->id)->get();
    return view('users.index', compact('users'));
  }

    public function edit()
  {

        $users = User::where('id','=', Auth ::user()->id)->first();
        //return view('users.edit', compact('users'));
        return view('users.edit', compact('users'));
  }

  public function update(Request $request,$id)
    {

        $users = User::find($id);
        $users->name =  $request->get('name');
        $users->email = $request->get('email');
        $users->phoneNo = $request->get('phoneNo');

        $users->save();

        return redirect('/userEdit')->with('success', 'User updated!');

    }

    public function adminIndex(Request $request)
    {
      $users= User::with('users')->where('user_id',Auth::user()->id)->get();
      return view('users.adminIndex', compact('users'));
    }

      public function edit2()
    {

          $users = User::where('id','=', Auth ::user()->id)->first();
          return view('users.edit2', compact('users'));
    }

    public function update2(Request $request,$id)
      {

          $users = User::find($id);
          $users->name =  $request->get('name');
          $users->email = $request->get('email');

          $users->save();

          return redirect('/adminProfile')->with('success', 'User updated!');

      }

      public function changePassword()
      {
          $users = User::where('id','=', Auth ::user()->id)->first();
          return view('users.changePassword',compact('users'));
      }

      public function updatePassword(Request $request)
      {
        if(!(Hash::check($request->get('old_password'),Auth::user()->password)))
        {
            return back()->with('error', 'Your old password does not match with what you provided');
        }
        if(strcmp($request->get('old_password'), $request->get('new_password')) == 0)
        {
          return back()->with('error', 'Your new password cannot be same with the current password');
        }
        if(strcmp($request->get('confirm_password'), $request->get('new_password')) != 0)
        {
          return back()->with('error', 'Your new password does not match with the confirm password');
        }
        $request->validate([
            'old_password' => 'required',
            'new_password' => 'required|string|min:8',
        ]);
        //save the Password update
        $user = Auth::user();
        $user->password = bcrypt($request->get('new_password'));
        $user->save();
        return redirect('/adminProfile')->with('success', 'Password successfully changed. An email has been sent.');
      }

      public function changePassword2()
      {
          $users = User::where('id','=', Auth ::user()->id)->first();
          return view('users.changePassword2',compact('users'));
      }

      public function updatePassword2(Request $request)
      {
        if(!(Hash::check($request->get('old_password'),Auth::user()->password)))
        {
            return back()->with('error', 'Your old password does not match with what you provided');
        }
        if(strcmp($request->get('old_password'), $request->get('new_password')) == 0)
        {
          return back()->with('error', 'Your new password cannot be same with the current password');
        }
        if(strcmp($request->get('confirm_password'), $request->get('new_password')) != 0)
        {
          return back()->with('error', 'Your new password does not match with the confirm password');
        }
        $request->validate([
            'old_password' => 'required',
            'new_password' => 'required|string|min:8',
        ]);
        //save the Password update
        $user = Auth::user();
        $user->password = bcrypt($request->get('new_password'));
        $user->save();
        return redirect('/userEdit')->with('success', 'Password successfully changed. An email has been sent.');
      }

  }

resources/views/users/adminIndex.blade.php
@extends('layouts.appAdmin')

@section('content')
    @if(\Session::has('success'))
        <div class="alert alert-success" role="alert">
            <p>{{ Session::get('success') }}</p>
        </div>
    @endif
    @if(\Session::has('error'))
        <div class="alert" role="alert">
            <p>{{ Session::get('error') }}</p>
        </div>
    @endif
<div class="container">
  <div class="row">
      <div class="col-sm-8 offset-sm-2">
          <h3 class="display-3">Profile</h3>


              <div class="form-group">

                  <label for="full_name">Full Name:</label>
                  {{ Auth::user()->name }}

              </div>
              <div class="form-group">
                  <label for="email">Email:</label>
                  {{ Auth::user()->email }}
              </div>

              <!--<div class="form-group">
                  <label for="password">Password:</label>
                  <input class="form-control" value="{{ Auth::user()->password }}"/>
              </div>-->

              <a href="{{ url('/users/edit2', $users->user_id = Auth::user()->user_id)}}" class="btn btn-primary btn-sm">Edit</a>
              <a href="{{ url('/changePassword')}}" class="btn btn-primary btn-sm">Change Password</a>

          </form>
      </div>
</div>
@endsection

resources/views/users/changePassword.blade.php
@extends('layouts.appAdmin')

@section('content')
<div class="container">
  <div class="row">
      <div class="col-sm-8 offset-sm-2">
          <h1 class="display-3">Change Password</h1>

          @if ($errors->any())
          <div class="alert alert-danger">
              <ul>
                  @foreach ($errors->all() as $error)
                  <li>{{ $error }}</li>
                  @endforeach
              </ul>
          </div>
          <br />
          @endif
            <form method="post" action="{{ url('/users/updatePassword') }}">

              @csrf
              <div class="form-group">
                  <label for="old_password">Old Password:</label>
                  <input type="password" class="form-control" name="old_password" />
              </div>
              <div class="form-group">
                  <label for="password">New Password:</label>
                  <input type="password" class="form-control" name="new_password" />
              </div>
              <div class="form-group">
                  <label for="confirm_password">New Password:</label>
                  <input type="password" class="form-control" name="confirm_password" />
              </div>

              <button type="submit" class="btn btn-primary">Update</button>
          </form>
      </div>
</div>
@endsection

resources/views/users/changePassword2.blade.php
@extends('layouts.appAdmin')

@section('content')
<div class="container">
  <div class="row">
      <div class="col-sm-8 offset-sm-2">
          <h1 class="display-3">Change Password</h1>

          @if ($errors->any())
          <div class="alert alert-danger">
              <ul>
                  @foreach ($errors->all() as $error)
                  <li>{{ $error }}</li>
                  @endforeach
              </ul>
          </div>
          <br />
          @endif
            <form method="post" action="{{ url('/users/updatePassword2') }}">

              @csrf
              <div class="form-group">
                  <label for="old_password">Old Password:</label>
                  <input type="password" class="form-control" name="old_password" />
              </div>
              <div class="form-group">
                  <label for="password">New Password:</label>
                  <input type="password" class="form-control" name="new_password" />
              </div>
              <div class="form-group">
                  <label for="confirm_password">New Password:</label>
                  <input type="password" class="form-control" name="confirm_password" />
              </div>

              <button type="submit" class="btn btn-primary">Update</button>
          </form>
      </div>
</div>
@endsection

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
  <div class="row">
      <div class="col-sm-8 offset-sm-2">
          <h1 class="display-3">Edit Profile</h1>

          @if ($errors->any())
          <div class="alert alert-danger">
              <ul>
                  @foreach ($errors->all() as $error)
                  <li>{{ $error }}</li>
                  @endforeach
              </ul>
          </div>
          <br />
          @endif
          <form method="post" action="{{ route('users.update', $users->id) }}">
            @method('PATCH')
              @csrf
              <div class="form-group">

                  <label for="name">Full Names:</label>
                  <input type="text" class="form-control" name="name" value= "{{ Auth::user()->name }}"/>
              </div>
              <div class="form-group">
                  <label for="email">Email:</label>
                  <input type="text" class="form-control" name="email" value="{{ Auth::user()->email }}"/>
              </div>
              <div class="form-group">
                  <label for="phoneNo">Phone No:</label>
                  <input type="text" class="form-control" name="phoneNo" value="{{ Auth::user()->phoneNo }}"/>
              </div>

              <button type="submit" class="btn btn-primary">Update</button>
          </form>
      </div>
</div>
@endsection

resources/views/users/edit2.blade.php
@extends('layouts.appAdmin')

@section('content')
<div class="container">
  <div class="row">
      <div class="col-sm-8 offset-sm-2">
          <h1 class="display-3">Edit Profile</h1>

          @if ($errors->any())
          <div class="alert alert-danger">
              <ul>
                  @foreach ($errors->all() as $error)
                  <li>{{ $error }}</li>
                  @endforeach
              </ul>
          </div>
          <br />
          @endif
            <form method="post" action="{{ url('/users/update2', $users->id) }}">
            @method('PATCH')
              @csrf
              <div class="form-group">

                  <label for="name">Full Names:</label>
                  <input type="text" class="form-control" name="name" value= "{{ Auth::user()->name }}"/>
              </div>
              <div class="form-group">
                  <label for="email">Email:</label>
                  <input type="text" class="form-control" name="email" value="{{ Auth::user()->email }}"/>
              </div>

              <button type="submit" class="btn btn-primary">Update</button>
          </form>
      </div>
</div>
@endsection

resources/views/users/index.blade.php
@extends('layouts.app')

@section('content')
@if(\Session::has('success'))
    <div class="alert alert-success" role="alert">
        <p>{{ Session::get('success') }}</p>
    </div>
@endif
@if(\Session::has('error'))
    <div class="alert" role="alert">
        <p>{{ Session::get('error') }}</p>
    </div>
@endif
<div class="container">
  <div class="row">
      <div class="col-sm-8 offset-sm-2">
          <h1 class="display-3">Profile</h1>

              <div class="form-group">

                  <label for="full_name">Full Name: </label>
                  {{ Auth::user()->name }}

              </div>
              <div class="form-group">
                  <label for="email">Email: </label>
                   {{ Auth::user()->email }}
              </div>
              <div class="form-group">
                  <label for="user_id">Unit No: </label>
                  {{ Auth::user()->user_id }}
              </div>
              <div class="form-group">
                  <label for="phoneNo">Phone No: </label>
                  {{ Auth::user()->phoneNo }}
              </div>

              <a href="{{ route('users.edit', $users->user_id = Auth::user()->user_id)}}" class="btn btn-primary btn-sm">Edit</a>
              <a href="{{ url('/changePassword2')}}" class="btn btn-primary btn-sm">Change Password</a>
          </form>
      </div>
</div>
@endsection