routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\VisitorController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('visitorrs', function () {
    return view('visitorrs');
});

Route::get('visitorr', function () {
    return view('visitorr');
});

Route::get('events', function () {
    return view('events');
});

Route::get('history', function () {
    return view('history');
});

Route::get('historyPreRegister', function () {
    return view('historyPreRegister');
});


Route::get('userEdit', function () {
    return view('userEdit');
});

Route::get('qrCode', function () {
    return view('qrCode');
});

Route::get('qr-code-g', function () {


    \QrCode::size(500)

            ->format('png')

            ->generate('HDTuto.com', public_path('images/qrcode.png'));

  return view('qrCode');

});

Route::get('homeAdmin', function () {
    return view('homeAdmin');
});

Route::get('CheckInVisitor', function () {
    return view('CheckInVisitor');
});

Route::get('RegInVisitor', function () {
    return view('RegInVisitor');
});

Route::get('reg_visitor', function () {
    return view('reg_visitor');
});

Route::get('CheckOutVisitor', function () {
    return view('CheckOutVisitor');
});

Route::get('reg_visitors', function () {
    return view('reg_visitors');
});


Route::get('historyAdmin', function () {
    return view('historyAdmin');
});

Route::get('adminProfile', function () {
    return view('adminProfile');
});

Route::resource('visitorrs','VisitorController');
Route::resource('events','EventController');
Route::resource('reg_visitors','RegVisitorController');
Route::resource('users','UserController');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/homes', 'HomeController@index')->name('homes');

Route::get('admin/home', 'HomeController@adminHome')->name('admin.home')->middleware('is_admin');

Route::get('/search2', 'VisitorController@search2')->name('Search2');

Route::get('/historyPreRegister', 'historyPreRegisterController@index')->name('historyPreRegister');

Route::get('/search3', 'EventController@search3')->name('Search3');

Route::get('/search4', 'CheckOutController@search4')->name('Search4');

Route::get('/CheckOutVisitor', 'CheckOutController@index')->name('CheckOutVisitor');

Route::get('/CheckInVisitor', 'CheckInController@index')->name('CheckInVisitor');

Route::get('/search', 'CheckInController@search')->name('CheckInVisitor');

Route::get('/search5', 'HistoryAdminVisitorController@search5')->name('Search5');

Route::get('/search6', 'RegVisitorController@search6')->name('Search6');

Route::get('/historyVisitor', 'HistoryVisitorController@index')->name('historyVisitor');

Route::get('/search7', 'HistoryVisitorController@search7')->name('Search7');

Route::get('/historyEvent', 'HistoryEventController@index')->name('historyEvent');

Route::get('/search8', 'HistoryEventController@search8')->name('Search8');

Route::get('/CheckOut', 'CheckOut2Controller@index2')->name('CheckOut');

Route::get('/search9', 'CheckOut2Controller@search9')->name('Search9');

Route::get('/edit/{id}', 'UserController@edit')->name('Edit');

Route::post('/update/{id}', 'UserController@update')->name('Update');

Route::get('/userEdit', 'UserController@index')->name('userEdit');

Route::get('users/edit2/{id}', 'UserController@edit2')->name('Edit2');

Route::patch('users/update2/{id}', 'UserController@update2')->name('update2');

Route::get('/adminProfile', 'UserController@adminIndex')->name('adminProfile');

Route::get('/changePassword', 'UserController@changePassword')->name('changePassword');

Route::post('users/updatePassword/', 'UserController@updatePassword')->name('updatePassword');

Route::get('/changePassword2', 'UserController@changePassword2')->name('changePassword2');

Route::post('users/updatePassword2/', 'UserController@updatePassword2')->name('updatePassword2');

//Route::get('/CheckInVisitor/edit2/{id}', 'CheckInController@edit2')->name('CheckInVisitor.edit2');

Route::get('active/{id}', 'CheckInController@active')->name('active');
Route::get('inactive/{id}', 'CheckInController@inactive')->name('inactive');

Route::get('active2/{id}', 'CheckOutController@active2')->name('active2');
Route::get('inactive2/{id}', 'CheckOutController@inactive2')->name('inactive2');

Route::get('active4/{id}', 'CheckOut2Controller@active4')->name('active4');
Route::get('inactive4/{id}', 'CheckOut2Controller@inactive4')->name('inactive4');

Route::get('/displayCheckIn/{token}', 'VisitorController@checkin')->name('displayCheckIn');
Route::post('/visitorCheckedIn', 'VisitorController@checkedin')->name('visitorCheckedIn');

Route::get('/displayCheckOut/{token}', 'VisitorController@checkout')->name('displayCheckOut');
Route::post('/visitorCheckedOut', 'VisitorController@checkedout')->name('visitorCheckedOut');

app/Event.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Event extends Model
{
    protected $fillable =
	[
	'type_event',
	'select_date',
	'select_time',
	'num_visitor',
  'unitNo',
  'user_id',
	];

  public function users()
  {

          return $this->belongsTo(User::class);
  }
}

app/Http/Controllers/EventController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Event;
use DB;
use Auth;

class EventController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //$events= Event::with('users')->where('user_id','1')->get();
		    //return view('events.index', compact('events'));
        $events= Event::with('users')->where('user_id',Auth::user()->id)->get();
        return view('events.index', compact('events'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Event $events)
    {
      $events->user_id = Auth::id();
        return view('events.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'type_event'=>'required',
            'select_date'=>'required',
            'select_time'=>'required',
 	          'num_visitor'=>'required',

        ]);

        $event = new Event([
            'type_event' => $request->get('type_event'),
            'select_date' => $request->get('select_date'),
            'select_time' => $request->get('select_time'),
            'num_visitor' => $request->get('num_visitor'),
            'unitNo' => Auth::user()->user_id,
            'user_id' => Auth::user()->id
        ]);
        $event->save();
        return redirect('/events')->with('success', 'Event saved!');


    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $event = Event::find($id);
        return view('events.edit', compact('event'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'type_event'=>'required',
            'select_date'=>'required',
            'select_time'=>'required',
	          'num_visitor'=>'required',

        ]);

        $event = Event::find($id);
        $event->type_event =  $request->get('type_event');
        $event->select_date = $request->get('select_date');
        $event->select_time = $request->get('select_time');
        $event->num_visitor = $request->get('num_visitor');
        $event->unitNo = Auth::user()->user_id;
        $event->user_id = Auth::user()->id;

        $event->save();

        return redirect('/events')->with('success', 'Event updated!');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $event = Event::find($id);
        $event->delete();

        return redirect('/events')->with('success', 'Event deleted!');

    }

    public function search3(Request $request)
    {
        $search= $request->get('search3');
        $events=DB::table('events')->where('type_event', 'like', '%'.$search.'%')->paginate(5);
        return view('events.index', compact('events'));
    }
}

resources/views/events/create.blade.php
@extends('layouts.app')

@section('content')
<head>

<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/css/bootstrap-datepicker.css" rel="stylesheet">
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/js/bootstrap-datepicker.js"></script>

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment.min.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/css/bootstrap-datetimepicker.min.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/js/bootstrap-datetimepicker.min.js"></script>
</head>

<style>
.col-20 {
float: left;
width: 20%;
margin-top: 6px;
}

.col-75 {
float: left;
width: 75%;
margin-top: 6px;
}
</style>

<div class="container">
<div class="row">
 <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3"><center>Register Event</center></h1>
  <div>

      <form method="post" action="{{ route('events.store') }}">
          @csrf
          <div class="col-20">
              <label for="type_event">Type of event:</label>
          </div>
          <div class="col-75">
            <select id="type_event" class="form-control" name="type_event">
                <option value="birthday">Birthday party</option>
                <option value="wedding">Wedding</option>
                <option value="openhouse">Open house</option>
                <option value="other">Other</option>
            </select>
          </div>

          <br>
          </br>

          <div class="col-20">
              <label for="select_date">Date:</label>
          </div>
          <div class="col-75">
              <input type="text" class="date form-control" name="select_date" />
          </div>

          <script type="text/javascript">
            $('.date').datepicker({
                format: 'dd/mm/yyyy'
                });
          </script>

          <br>
          </br>

          <div class="col-20">
              <label for="select_time">Time:</label>
          </div>
          <div class="col-75">
              <input type="text" class="timepicker form-control" name="select_time"/>
          </div>

          <script type="text/javascript">
            $('.timepicker').datetimepicker({
                format: 'HH:mm'
              });
          </script>

          <br>
          </br>

          <div class="col-20">
              <label for="num_visitor">Number of visitor:</label>
          </div>
          <div class="col-75">
            <select id="num_visitor" class="form-control" name="num_visitor">
                <option value="1 to 99">1 - 99</option>
                <option value="100 - 999">100 - 999</option>
                <option value="More than 999">More than 999</option>
            </select>
          </div>

          <br>
          </br>

          <center>
          <button type="submit" class="btn btn-success">Register</button>
          </center>

      </form>
  </div>
</div>
</div>
</div>
@endsection

resources/views/events/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h1 class="display-3">Update a visitor</h1>

        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        <br />
        @endif
        <form method="post" action="{{ route('events.update', $event->id) }}">
            @method('PATCH')
            @csrf
            <div class="form-group">

                <label for="type_event">Type of event:</label>
                <input type="text" class="form-control" name="type_event" value={{ $event->type_event }} />
            </div>

            <div class="form-group">
                <label for="select_date">Date:</label>
                <input type="text" class="form-control" name="select_date" value={{ $event->select_date }} />
            </div>

            <div class="form-group">
                <label for="select_time">Time:</label>
                <input type="text" class="form-control" name="select_time" value={{ $event->select_time }} />
            </div>
            <div class="form-group">
                <label for="num_visitor">Number of visitor:</label>
                <input type="text" class="form-control" name="num_visitor" value={{ $event->num_visitor }} />
            </div>

            <div>
            <button type="submit" class="btn btn-primary">Update</button>
          </div>
        </form>
    </div>
</div>
@endsection

resources/views/events/historyEvent.blade.php
@extends('layouts.appAdmin3')

@section('content')
  <div class="container">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
      <div class="row">
  <div class="col-sm-12">
      <h1 class="display-3">Events</h1>
      <table class="table table-striped">

        <div class="col-md-5">
          <form action="/search8" method="get">
          <div class="input-group">
            <button type="submit"a href="http://localhost:8000/historyVisitor"><i class="fa fa-arrow-left" style="font-size:15px;color:black" ></i></a></button>
            <input type="search8" name="search8" class="form-control">
            <span class="input-group-prepend">
              <button type="submit" class="btn btn-primary">Search</button>
            </span>
          </div>
          </form>
        </div>

        <br>
      <thead>
          <tr>
            <td>No</td>
            <td>Type of events</td>
            <td>Date of events</td>
            <td>Time of events</td>
            <td>Number of visitor</td>
            <td>Unit No</td>
          </tr>
      </thead>
      <tbody>
        @foreach($events as $event)
        <tr>
            <td>{{$loop->iteration}}</td>
            <td>{{$event->type_event}}</td>
            <td>{{$event->select_date}}</td>
            <td>{{$event->select_time}}</td>
            <td>{{$event->num_visitor}}</td>
            <td>{{$event->unitNo}}</td>
        </tr>
        @endforeach
      </tbody>
    </table>
  <div>
  </div>
  </div>
  @endsection

  <div class="col-sm-12">

    @if(session()->get('success'))
      <div class="alert alert-success">
        {{ session()->get('success') }}
      </div>
    @endif

resources/views/events/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <div class="row">
<div class="col-sm-12">
    <h1 class="display-3">Events</h1>
    <table class="table table-striped">

      <div class="col-md-5">
        <form action="/search3" method="get">
        <div class="input-group">
          <button type="submit"a href="http://localhost:8000/events"><i class="fa fa-arrow-left" style="font-size:15px;color:black" ></i></a></button>
          <input type="search3" name="search3" class="form-control">
          <span class="input-group-prepend">
            <button type="submit" class="btn btn-primary">Search</button>
          </span>
        </div>
        </form>
      </div>

      <br>

    <thead>
        <tr>
          <td>ID</td>
          <td>Type of events</td>
          <td>Date of events</td>
          <td>Time of events</td>
          <td>Number of visitor</td>
          <td>Unit No</td>
          <td colspan = 2>Actions</td>
        </tr>
    </thead>
    <tbody>
        @foreach($events as $event)
        <tr>
            <td>{{$event->id}}</td>
            <td>{{$event->type_event}}</td>
            <td>{{$event->select_date}}</td>
            <td>{{$event->select_time}}</td>
            <td>{{$event->num_visitor}}</td>
            <td>{{$event->unitNo}}</td>
            <td>
                <a href="{{ route('events.edit',$event->id)}}" button class="btn btn-primary"><i class="fa fa-pencil"></i></a>
            </td>
            <td>
                <form action="{{ route('events.destroy', $event->id)}}" method="post">
                  @csrf
                  @method('DELETE')
                  <button class="btn btn-danger" onclick="return confirm('Are you sure to delete?')"><i class="fa fa-trash-o"></i></button>
                </form>
            </td>
        </tr>
        @endforeach
    </tbody>
  </table>
<div>
</div>
</div>
@endsection

<div class="col-sm-12">

  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}
    </div>
  @endif