routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\VisitorController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('visitorrs', function () {
    return view('visitorrs');
});

Route::get('visitorr', function () {
    return view('visitorr');
});

Route::get('events', function () {
    return view('events');
});

Route::get('history', function () {
    return view('history');
});

Route::get('historyPreRegister', function () {
    return view('historyPreRegister');
});


Route::get('userEdit', function () {
    return view('userEdit');
});

Route::get('qrCode', function () {
    return view('qrCode');
});

Route::get('qr-code-g', function () {


    \QrCode::size(500)

            ->format('png')

            ->generate('HDTuto.com', public_path('images/qrcode.png'));

  return view('qrCode');

});

Route::get('homeAdmin', function () {
    return view('homeAdmin');
});

Route::get('CheckInVisitor', function () {
    return view('CheckInVisitor');
});

Route::get('RegInVisitor', function () {
    return view('RegInVisitor');
});

Route::get('reg_visitor', function () {
    return view('reg_visitor');
});

Route::get('CheckOutVisitor', function () {
    return view('CheckOutVisitor');
});

Route::get('reg_visitors', function () {
    return view('reg_visitors');
});


Route::get('historyAdmin', function () {
    return view('historyAdmin');
});

Route::get('adminProfile', function () {
    return view('adminProfile');
});

Route::resource('visitorrs','VisitorController');
Route::resource('events','EventController');
Route::resource('reg_visitors','RegVisitorController');
Route::resource('users','UserController');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/homes', 'HomeController@index')->name('homes');

Route::get('admin/home', 'HomeController@adminHome')->name('admin.home')->middleware('is_admin');

Route::get('/search2', 'VisitorController@search2')->name('Search2');

Route::get('/historyPreRegister', 'historyPreRegisterController@index')->name('historyPreRegister');

Route::get('/search3', 'EventController@search3')->name('Search3');

Route::get('/search4', 'CheckOutController@search4')->name('Search4');

Route::get('/CheckOutVisitor', 'CheckOutController@index')->name('CheckOutVisitor');

Route::get('/CheckInVisitor', 'CheckInController@index')->name('CheckInVisitor');

Route::get('/search', 'CheckInController@search')->name('CheckInVisitor');

Route::get('/search5', 'HistoryAdminVisitorController@search5')->name('Search5');

Route::get('/search6', 'RegVisitorController@search6')->name('Search6');

Route::get('/historyVisitor', 'HistoryVisitorController@index')->name('historyVisitor');

Route::get('/search7', 'HistoryVisitorController@search7')->name('Search7');

Route::get('/historyEvent', 'HistoryEventController@index')->name('historyEvent');

Route::get('/search8', 'HistoryEventController@search8')->name('Search8');

Route::get('/CheckOut', 'CheckOut2Controller@index2')->name('CheckOut');

Route::get('/search9', 'CheckOut2Controller@search9')->name('Search9');

Route::get('/edit/{id}', 'UserController@edit')->name('Edit');

Route::post('/update/{id}', 'UserController@update')->name('Update');

Route::get('/userEdit', 'UserController@index')->name('userEdit');

Route::get('users/edit2/{id}', 'UserController@edit2')->name('Edit2');

Route::patch('users/update2/{id}', 'UserController@update2')->name('update2');

Route::get('/adminProfile', 'UserController@adminIndex')->name('adminProfile');

Route::get('/changePassword', 'UserController@changePassword')->name('changePassword');

Route::post('users/updatePassword/', 'UserController@updatePassword')->name('updatePassword');

Route::get('/changePassword2', 'UserController@changePassword2')->name('changePassword2');

Route::post('users/updatePassword2/', 'UserController@updatePassword2')->name('updatePassword2');

//Route::get('/CheckInVisitor/edit2/{id}', 'CheckInController@edit2')->name('CheckInVisitor.edit2');

Route::get('active/{id}', 'CheckInController@active')->name('active');
Route::get('inactive/{id}', 'CheckInController@inactive')->name('inactive');

Route::get('active2/{id}', 'CheckOutController@active2')->name('active2');
Route::get('inactive2/{id}', 'CheckOutController@inactive2')->name('inactive2');

Route::get('active4/{id}', 'CheckOut2Controller@active4')->name('active4');
Route::get('inactive4/{id}', 'CheckOut2Controller@inactive4')->name('inactive4');

Route::get('/displayCheckIn/{token}', 'VisitorController@checkin')->name('displayCheckIn');
Route::post('/visitorCheckedIn', 'VisitorController@checkedin')->name('visitorCheckedIn');

Route::get('/displayCheckOut/{token}', 'VisitorController@checkout')->name('displayCheckOut');
Route::post('/visitorCheckedOut', 'VisitorController@checkedout')->name('visitorCheckedOut');

app/RegVisitor.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class RegVisitor extends Model
{
    protected $fillable =
	[
	'full_name',
	'ic_no',
	'phone_number',
	'plate_number',
  'unitNo',
  'date',
  'status3',
  'status4'
	];

  public function users()
  {

          return $this->belongsTo(User::class);
  }

}

app/Http/Controllers/RegVisitorController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\RegVisitor;
use DB;
use Auth;
use App\User;

class RegVisitorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        //$reg_visitors= RegVisitor::Latest('id')->get();
		    //return view('reg_visitors.index', compact('reg_visitors'));
        $reg_visitors= RegVisitor::all()->where('unitNo', Auth::user()->user_id);
        return view('reg_visitors.index', compact('reg_visitors'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $unitno = DB::table('users')->orderBy('user_id')->get();
        return view('reg_visitors.create', compact('unitno'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {


            $reg_visitor = new RegVisitor([
            'full_name' => $request->get('full_name'),
            'ic_no' => $request->get('ic_no'),
            'phone_number' => $request->get('phone_number'),
	          'plate_number' => $request->get('plate_number'),
            'unitNo' => $request->get('unitNo'),
            'date' => $request->get('date'),
            'select_date' => $request->get('select_date'),

        ]);
        $reg_visitor->save();
        return redirect('/CheckInVisitor')->with('success', 'Contact saved!');


    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $reg_visitor = RegVisitor::find($id);
        return view('reg_visitors.edit', compact('reg_visitor'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $reg_visitor = RegVisitor::find($id);
        $reg_visitor->full_name =  $request->get('full_name');
        $reg_visitor->ic_no = $request->get('ic_no');
        $reg_visitor->phone_number = $request->get('phone_number');
		    $reg_visitor->plate_number = $request->get('plate_number');
        $reg_visitor->unitNo = $request->get('unitNo');
        $reg_visitor->save();

        return redirect('/reg_visitors')->with('success', 'Visitor updated!');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $reg_visitor = RegVisitor::find($id);
        $reg_visitor->delete();

        return redirect('/reg_visitors')->with('success', 'Visitor deleted!');

    }

    public function search6(Request $request)
    {
        $search6= $request->get('search6');
        $reg_visitors=DB::table('reg_visitors')->where('full_name', 'like', '%'.$search6.'%')->paginate(9);
		     return view('reg_visitors.index', compact('reg_visitors'));
    }

}

resources/views/reg_visitors/CheckOut.blade.php
  @extends('layouts.appAdmin2')

  @section('content')
  <div class="container">
    <div class="container">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
      <script src="https://rawgit.com/schmich/instascan-builds/master/instascan.min.js"></script>

  <style>
  .preview{
     width:200px;
     height: 200px;
     margin:0px auto;

  }
  </style>

      <video id="preview"></video>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <div class="row">
    <div class="col-sm-15"><a class="nav-link" href="http://localhost:8000/CheckOut"><b>Visitors</b></a>
    </div>

    <div class="col-md-5">
      <form action="/search9" method="get">
      <div class="input-group">
        <input type="search9" name="search9" class="form-control">
        <span class="input-group-prepend">
          <button type="submit" class="btn btn-primary">Search</button>
        </span>
      </div>
      </form>
    </div>

    <script type="text/javascript">
        var scanner = new Instascan.Scanner({ video: document.getElementById('preview'), scanPeriod: 5, mirror: false });
        scanner.addListener('scan',function(content){
            //alert(content);
            window.location.href=content;
        });
        Instascan.Camera.getCameras().then(function (cameras){
            if(cameras.length>0){
                scanner.start(cameras[0]);
                $('[name="options"]').on('change',function(){
                    if($(this).val()==1){
                        if(cameras[0]!=""){
                            scanner.start(cameras[0]);
                        }else{
                            alert('No Front camera found!');
                        }
                    }else if($(this).val()==2){
                        if(cameras[1]!=""){
                            scanner.start(cameras[1]);
                        }else{
                            alert('No Back camera found!');
                        }
                    }
                });
            }else{
                console.error('No cameras found.');
                alert('No cameras found.');
            }
        }).catch(function(e){
            console.error(e);
            alert(e);
        });
    </script>

    <table class="table table-striped">
    <thead>
        <tr>
          <td>ID</td>
          <td>Full Name</td>
          <td>Phone Number</td>
          <td>Plate Number</td>
          <td>Unit No</td>
          <td>Status</td>
          <td colspan = 2>Actions</td>
        </tr>
    </thead>
    <tbody>
        @foreach($reg_visitors as $reg_visitor)
          <tr>
            <td>{{$reg_visitor->id}}</td>
            <td>{{$reg_visitor->full_name}}</td>
            <td>{{$reg_visitor->phone_number}}</td>
            <td>{{$reg_visitor->plate_number}}</td>
            <td>{{$reg_visitor->unitNo}}</td>
            <td>{{$reg_visitor->status4 == "CheckOut" ? 'Check Out' : 'Pending'}}</td>
            <td>
              @if ($reg_visitor->status4=="CheckOut")
                  <a href="{{ route('inactive4', $reg_visitor->id)}}" class="fa fa-arrow-up"</a>
              @else
                  <a href="{{ route('active4', $reg_visitor->id)}}" class="fa fa-arrow-down"</a>
              @endif
            </td>
          </tr>
        @endforeach
    </tbody>
    </table>
    </div>
  </div>
  @endsection

resources/views/reg_visitors/create.blade.php
@extends('layouts.appAdmin')

@section('content')
<head>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/css/bootstrap-datepicker.css" rel="stylesheet">
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/js/bootstrap-datepicker.js"></script>
</head>
<style>
.col-20 {
float: left;
width: 20%;
margin-top: 6px;
}

.col-75 {
float: left;
width: 75%;
margin-top: 6px;
}
</style>

<div class="container">
<div class="row">
 <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3"><center>Register Visitor</center></h1>
  <div>
    @if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    <br />
    @endif

      <form method="post" action="{{ route('reg_visitors.store') }}">
          @csrf
          <div class="col-20">
              <label for="full_name">Full Name</label>
          </div>
          <div class="col-75">
              <input type="text" class="form-control" name="full_name"/>
          </div>

          <br>
          </br>

          <div class="col-20">
              <label for="ic_no">IC Number</label>
          </div>
          <div class="col-75">
              <input type="text" class="form-control" name="ic_no"/>
          </div>

          <br>
          </br>

          <div class="col-20">
              <label for="phone_number">Phone Number</label>
          </div>
          <div class="col-75">
              <input type="text" class="form-control" name="phone_number"/>
          </div>

          <br>
          </br>

	        <div class="col-20">
              <label for="plate_number">Plate Number</label>
          </div>
          <div class="col-75">
              <input type="text" class="form-control" name="plate_number"/>
          </div>

          <br>
          </br>

          <div class="col-20">
              <label for="date">Date</label>
          </div>
          <div class="col-75">
              <input type="text" class="date form-control" name="date" />
          </div>

          <script type="text/javascript">
            $('.date').datepicker({
                format: 'dd/mm/yyyy'
                });
          </script>

          <br>
          </br>

          <div class="col-20">
          <label for="unitNo">Unit Number</label>
          </div>
          <div class="col-75">
            <select id="select_unitNo" class="form-control" name="unitNo">
              @foreach($unitno as $unit)
                @if($unit->user_id != '0')
                <option value="{{$unit->user_id}}">{{$unit->user_id}}</option>
                @endif
              @endforeach
            </select>
          </div>

          <br>
          <br>
          </br>
          </br>

          <center>
          <button type="submit" class="btn btn-success">Register</button>
          </center>

      </form>
  </div>
</div>
</div>
</div>
@endsection

resources/views/reg_visitors/displayPreCheckIn.blade.php
@extends('layouts.appAdmin')

@section('content')
<head>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/css/bootstrap-datepicker.css" rel="stylesheet">
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/js/bootstrap-datepicker.js"></script>
</head>
<style>
.col-20 {
float: left;
width: 20%;
margin-top: 6px;
}

.col-75 {
float: left;
width: 75%;
margin-top: 6px;
}
</style>

<div class="container">
<div class="row">
 <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3"><center>Visitor</center></h1>
  <div>

      <form method="post" action="/visitorPreCheckedIn">
          @csrf
          <input name=token value="{{ $checkin->token }}" hidden>
          <div class="col-20">
              <label for="full_name">Visitor Name:</label>
          </div>
          <div class="col-75">
              {{ $reg_visitors->full_name}}
          </div>

          <br>
          </br>

          <div class="col-20">
              <label for="ic_no">IC Number:</label>
          </div>
          <div class="col-75">
              {{ $reg_visitors->ic_no}}
          </div>

          <br>
          </br>

          <div class="col-20">
              <label for="phone_number">Phone Number:</label>
          </div>
          <div class="col-75">
          </div>
            {{ $reg_visitors->phone_number}}
          <br>
          </br>

          <div class="col-20">
              <label for="plate_number">Plate No:</label>
          </div>
          <div class="col-75">
              {{ $reg_visitors->plate_number}}
          </div>


          <br>
          </br>

	        <div class="col-20">
              <label for="unitNo">Unit No:</label>
          </div>
          <div class="col-75">
              {{ $reg_visitors->unitNo}}
          </div>



          <br>
          <br>
          </br>
          </br>

          <center>
          <button type="submit" class="btn btn-success">Check In</button>
          </center>

      </form>
  </div>
</div>
</div>
</div>
@endsection

resources/views/reg_visitors/edit.blade.php
@extends('layouts.appAdmin')

@section('content')
<div class="container">
<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h1 class="display-3">Update a visitor</h1>

        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        <br />
        @endif
        <form method="post" action="{{ route('reg_visitors.update', $reg_visitor->id) }}">
            @method('PATCH')
            @csrf
            <div class="form-group">

                <label for="full_name">Full Name:</label>
                <input type="text" class="form-control" name="full_name" value={{ $reg_visitor->full_name }} />
            </div>

            <div class="form-group">
                <label for="ic_no">IC NO:</label>
                <input type="text" class="form-control" name="ic_no" value={{ $reg_visitor->ic_no }} />
            </div>
            <div class="form-group">
                <label for="phone_number">Phone Number:</label>
                <input type="text" class="form-control" name="phone_number" value={{ $reg_visitor->phone_number }} />
            </div>
            <div class="form-group">
                <label for="plate_number">Plate Number:</label>
                <input type="text" class="form-control" name="plate_number" value={{ $reg_visitor->plate_number }} />
            </div>
            <div class="form-group">
                <label for="unitNo">Unit No:</label>
                <input type="text" class="form-control" name="unitNo" value={{ $reg_visitor->unitNo }} />
            </div>

            <button type="submit" class="btn btn-primary">Update</button>
        </form>
    </div>
</div>
@endsection

resources/views/reg_visitors/historyPreRegister.blade.php
@extends('layouts.appAdmin3')

@section('content')
<div class="container">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <div class="row">
<div class="col-sm-12">
    <h3 class="display-3">Pre-register List</h3>
    <table class="table table-striped">

      <br>

    <thead>
        <tr>
          <td>No</td>
          <td>Full Name</td>
          <td>Phone Number</td>
          <td>Plate Number</td>
          <td>Unit No</td>
          <td>Date</td>
          <td colspan = 2>Status</td>
        </tr>
    </thead>
    <tbody>
      @foreach($reg_visitors as $reg_visitor)

        <td>  {{$loop->iteration}}</td>
        <td>  {{$reg_visitor->full_name}} </td>
        <td>  {{$reg_visitor->phone_number}} </td>
        <td>  {{$reg_visitor->plate_number}} </td>
        <td>  {{$reg_visitor->unitNo}} </td>
        <td>  {{$reg_visitor->date}} </td>
        <td>  {{$reg_visitor->status3}} </td>
        <td>  {{$reg_visitor->status4}} </td>

        </tr>
        @endforeach
    </tbody>
  </table>
<div>
</div>
</div>
@endsection


<div class="col-sm-12">

  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}
    </div>
  @endif

resources/views/reg_visitors/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <div class="row">
<div class="col-sm-12">
    <h3 class="display-3">Pre-register List</h3>
    <table class="table table-striped">

      <div class="col-md-5">
        <form action="/search6" method="get">
        <div class="input-group">
          <button type="submit"a href="http://localhost:8000/reg_visitors"><i class="fa fa-arrow-left" style="font-size:15px;color:black" ></i></a></button>
          <input type="search6" name="search6" class="form-control">
          <span class="input-group-prepend">
            <button type="submit" class="btn btn-primary">Search</button>
          </span>
        </div>
        </form>
      </div>

      <br>

    <thead>
        <tr>
          <td>No</td>
          <td>Full Name</td>
          <td>Phone Number</td>
          <td>Plate Number</td>
          <td>Unit No</td>
          <td>Date</td>
          <td colspan = 2>Status</td>
        </tr>
    </thead>
    <tbody>
      @foreach($reg_visitors as $reg_visitor)

        <td>  {{$loop->iteration}}</td>
        <td>  {{$reg_visitor->full_name}} </td>
        <td>  {{$reg_visitor->phone_number}} </td>
        <td>  {{$reg_visitor->plate_number}} </td>
        <td>  {{$reg_visitor->unitNo}} </td>
        <td>  {{$reg_visitor->date}} </td>
        <td>  {{$reg_visitor->status3}} </td>
        <td>  {{$reg_visitor->status4}} </td>

        </tr>
        @endforeach
    </tbody>
  </table>
<div>
</div>
</div>
@endsection


<div class="col-sm-12">

  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}
    </div>
  @endif