routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\VisitorController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('visitorrs', function () {
    return view('visitorrs');
});

Route::get('visitorr', function () {
    return view('visitorr');
});

Route::get('events', function () {
    return view('events');
});

Route::get('history', function () {
    return view('history');
});

Route::get('historyPreRegister', function () {
    return view('historyPreRegister');
});


Route::get('userEdit', function () {
    return view('userEdit');
});

Route::get('qrCode', function () {
    return view('qrCode');
});

Route::get('qr-code-g', function () {


    \QrCode::size(500)

            ->format('png')

            ->generate('HDTuto.com', public_path('images/qrcode.png'));

  return view('qrCode');

});

Route::get('homeAdmin', function () {
    return view('homeAdmin');
});

Route::get('CheckInVisitor', function () {
    return view('CheckInVisitor');
});

Route::get('RegInVisitor', function () {
    return view('RegInVisitor');
});

Route::get('reg_visitor', function () {
    return view('reg_visitor');
});

Route::get('CheckOutVisitor', function () {
    return view('CheckOutVisitor');
});

Route::get('reg_visitors', function () {
    return view('reg_visitors');
});


Route::get('historyAdmin', function () {
    return view('historyAdmin');
});

Route::get('adminProfile', function () {
    return view('adminProfile');
});

Route::resource('visitorrs','VisitorController');
Route::resource('events','EventController');
Route::resource('reg_visitors','RegVisitorController');
Route::resource('users','UserController');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/homes', 'HomeController@index')->name('homes');

Route::get('admin/home', 'HomeController@adminHome')->name('admin.home')->middleware('is_admin');

Route::get('/search2', 'VisitorController@search2')->name('Search2');

Route::get('/historyPreRegister', 'historyPreRegisterController@index')->name('historyPreRegister');

Route::get('/search3', 'EventController@search3')->name('Search3');

Route::get('/search4', 'CheckOutController@search4')->name('Search4');

Route::get('/CheckOutVisitor', 'CheckOutController@index')->name('CheckOutVisitor');

Route::get('/CheckInVisitor', 'CheckInController@index')->name('CheckInVisitor');

Route::get('/search', 'CheckInController@search')->name('CheckInVisitor');

Route::get('/search5', 'HistoryAdminVisitorController@search5')->name('Search5');

Route::get('/search6', 'RegVisitorController@search6')->name('Search6');

Route::get('/historyVisitor', 'HistoryVisitorController@index')->name('historyVisitor');

Route::get('/search7', 'HistoryVisitorController@search7')->name('Search7');

Route::get('/historyEvent', 'HistoryEventController@index')->name('historyEvent');

Route::get('/search8', 'HistoryEventController@search8')->name('Search8');

Route::get('/CheckOut', 'CheckOut2Controller@index2')->name('CheckOut');

Route::get('/search9', 'CheckOut2Controller@search9')->name('Search9');

Route::get('/edit/{id}', 'UserController@edit')->name('Edit');

Route::post('/update/{id}', 'UserController@update')->name('Update');

Route::get('/userEdit', 'UserController@index')->name('userEdit');

Route::get('users/edit2/{id}', 'UserController@edit2')->name('Edit2');

Route::patch('users/update2/{id}', 'UserController@update2')->name('update2');

Route::get('/adminProfile', 'UserController@adminIndex')->name('adminProfile');

Route::get('/changePassword', 'UserController@changePassword')->name('changePassword');

Route::post('users/updatePassword/', 'UserController@updatePassword')->name('updatePassword');

Route::get('/changePassword2', 'UserController@changePassword2')->name('changePassword2');

Route::post('users/updatePassword2/', 'UserController@updatePassword2')->name('updatePassword2');

//Route::get('/CheckInVisitor/edit2/{id}', 'CheckInController@edit2')->name('CheckInVisitor.edit2');

Route::get('active/{id}', 'CheckInController@active')->name('active');
Route::get('inactive/{id}', 'CheckInController@inactive')->name('inactive');

Route::get('active2/{id}', 'CheckOutController@active2')->name('active2');
Route::get('inactive2/{id}', 'CheckOutController@inactive2')->name('inactive2');

Route::get('active4/{id}', 'CheckOut2Controller@active4')->name('active4');
Route::get('inactive4/{id}', 'CheckOut2Controller@inactive4')->name('inactive4');

Route::get('/displayCheckIn/{token}', 'VisitorController@checkin')->name('displayCheckIn');
Route::post('/visitorCheckedIn', 'VisitorController@checkedin')->name('visitorCheckedIn');

Route::get('/displayCheckOut/{token}', 'VisitorController@checkout')->name('displayCheckOut');
Route::post('/visitorCheckedOut', 'VisitorController@checkedout')->name('visitorCheckedOut');

app/Visitorr.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;
class Visitorr extends Model
{
    protected $fillable =
	[
  'visitorrs_id',
	'full_name',
	'ic_no',
	'email',
	'phone_number',
	'type_vehicle',
	'plate_number',
  'status',
  'status2',
  'unitNo',
  'date',
  'user_id',

	];

  //public function users()
  //{
  //  return $this->belongsTo ('App\User');
  //}

  public function users()
  {

          return $this->belongsTo(User::class);
  }

}

resources/views/visitorrs/CheckInVisitor.blade.php
  @extends('layouts.appAdmin')

  @section('content')
  <div class="container">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <script src="https://rawgit.com/schmich/instascan-builds/master/instascan.min.js"></script>

<style>
.preview{
   width:200px;
   height: 200px;
   margin:0px auto;

}
</style>

    <video id="preview"></video>

    <div class="row">
    <div class="col-sm-15"><a class="nav-link" href="http://localhost:8000/CheckInVisitor"><b>Visitors</b></a>
    </div>

    <div class="col-md-5">
      <form action="/search" method="get">
      <div class="input-group">
        <input type="search" name="search" class="form-control">
        <span class="input-group-prepend">
          <button type="submit" class="btn btn-primary">Search</button>
        </span>
      </div>
      </form>
    </div>

    <script type="text/javascript">
        var scanner = new Instascan.Scanner({ video: document.getElementById('preview'), scanPeriod: 5, mirror: false });
        scanner.addListener('scan',function(content){
            //alert(content);
            window.location.href=content;
        });
        Instascan.Camera.getCameras().then(function (cameras){
            if(cameras.length>0){
                scanner.start(cameras[0]);
                $('[name="options"]').on('change',function(){
                    if($(this).val()==1){
                        if(cameras[0]!=""){
                            scanner.start(cameras[0]);
                        }else{
                            alert('No Front camera found!');
                        }
                    }else if($(this).val()==2){
                        if(cameras[1]!=""){
                            scanner.start(cameras[1]);
                        }else{
                            alert('No Back camera found!');
                        }
                    }
                });
            }else{
                console.error('No cameras found.');
                alert('No cameras found.');
            }
        }).catch(function(e){
            console.error(e);
            alert(e);
        });
    </script>


    <table class="table table-striped">
    <thead>
        <tr>
          <td>ID</td>
          <td>Full Name</td>
          <td>IC No</td>
          <td>Phone Number</td>
          <td>Plate Number</td>
          <td>Unit No</td>
          <td>Status</td>


          <td colspan = 2>Actions</td>
        </tr>
    </thead>
    <tbody>
        @foreach($visitorrs as $visitorr)
          <tr>
            <td>{{$visitorr->id}}</td>
            <td>{{$visitorr->full_name}}</td>
            <td>{{$visitorr->ic_no}}</td>
            <td>{{$visitorr->phone_number}}</td>
            <td>{{$visitorr->plate_number}}</td>
            <td>{{$visitorr->unitNo}}</td>
            <td>{{$visitorr->status =="CheckIn" ? 'Check In' : 'Pending'}}</td>
            <td>
              @if ($visitorr->status=="CheckIn")
                  <a href="{{ route('inactive', $visitorr->id)}}" class="fa fa-arrow-up"</a>
              @else
                  <a href="{{ route('active', $visitorr->id)}}" class="fa fa-arrow-down"</a>
              @endif
            </td>
          </tr>
        @endforeach
    </tbody>
    </table>
    </div>
  </div>
  @endsection

resources/views/visitorrs/CheckOutVisitor.blade.php
  @extends('layouts.appAdmin2')

  @section('content')
  <div class="container">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <script src="https://rawgit.com/schmich/instascan-builds/master/instascan.min.js"></script>

<style>
.preview{
   width:200px;
   height: 200px;
   margin:0px auto;

}
</style>

    <video id="preview"></video>
  
    <div class="row">
    <div class="col-sm-15"><a class="nav-link" href="http://localhost:8000/CheckOutVisitor"><b>Visitors</b></a>
    </div>

    <div class="col-md-5">
      <form action="/search4" method="get">
      <div class="input-group">
        <input type="search4" name="search4" class="form-control">
        <span class="input-group-prepend">
          <button type="submit" class="btn btn-primary">Search</button>
        </span>
      </div>
      </form>
    </div>


    <script type="text/javascript">
        var scanner = new Instascan.Scanner({ video: document.getElementById('preview'), scanPeriod: 5, mirror: false });
        scanner.addListener('scan',function(content){
            //alert(content);
            window.location.href=content;
        });
        Instascan.Camera.getCameras().then(function (cameras){
            if(cameras.length>0){
                scanner.start(cameras[0]);
                $('[name="options"]').on('change',function(){
                    if($(this).val()==1){
                        if(cameras[0]!=""){
                            scanner.start(cameras[0]);
                        }else{
                            alert('No Front camera found!');
                        }
                    }else if($(this).val()==2){
                        if(cameras[1]!=""){
                            scanner.start(cameras[1]);
                        }else{
                            alert('No Back camera found!');
                        }
                    }
                });
            }else{
                console.error('No cameras found.');
                alert('No cameras found.');
            }
        }).catch(function(e){
            console.error(e);
            alert(e);
        });
    </script>

    <table class="table table-striped">
    <thead>
        <tr>
          <td>ID</td>
          <td>Full Name</td>
          <td>IC No</td>
          <td>Phone Number</td>
          <td>Plate Number</td>
          <td>Unit No</td>
          <td>Status</td>


          <td colspan = 2>Actions</td>
        </tr>
    </thead>
    <tbody>
        @foreach($visitorrs as $visitorr)
          <tr>
            <td>{{$visitorr->id}}</td>
            <td>{{$visitorr->full_name}}</td>
            <td>{{$visitorr->ic_no}}</td>
            <td>{{$visitorr->phone_number}}</td>
            <td>{{$visitorr->plate_number}}</td>
            <td>{{$visitorr->unitNo}}</td>
            <td>{{$visitorr->status2 == "CheckOut" ? 'Check Out' : 'Pending'}}</td>
            <td>
              @if ($visitorr->status2=="CheckOut")
                  <a href="{{ route('inactive2', $visitorr->id)}}" class="fa fa-arrow-up"</a>
              @else
                  <a href="{{ route('active2', $visitorr->id)}}" class="fa fa-arrow-down"</a>
              @endif
            </td>
          </tr>
        @endforeach
    </tbody>
    </table>
    </div>
  </div>
  @endsection

resources/views/visitorrs/create.blade.php
@extends('layouts.app')

@section('content')
<head>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/css/bootstrap-datepicker.css" rel="stylesheet">
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/js/bootstrap-datepicker.js"></script>
</head>
<style>
.col-20 {
float: left;
width: 20%;
margin-top: 6px;
}

.col-75 {
float: left;
width: 75%;
margin-top: 6px;
}
</style>

<div class="container">
<div class="row">
 <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3"><center>Register Visitor</center></h1>
  <div>

      <form method="post" action="{{ route('visitorrs.store') }}">
          @csrf
          <div class="col-20">
              <label for="full_name">Visitor Name*</label>
          </div>
          <div class="col-75">
              <input type="text" class="form-control" name="full_name"/>
          </div>

          <br>
          </br>

          <div class="col-20">
              <label for="ic_no">IC Number*</label>
          </div>
          <div class="col-75">
              <input type="text" class="form-control" name="ic_no"/>
          </div>

          <br>
          </br>

          <div class="col-20">
              <label for="email">Email</label>
          </div>
          <div class="col-75">
              <input type="text" class="form-control" name="email"/>
          </div>

          <br>
          </br>

          <div class="col-20">
              <label for="phone_number">Phone Number</label>
          </div>
          <div class="col-75">
              <input type="text" class="form-control" name="phone_number"/>
          </div>

          <br>
          </br>

          <div class="col-20">
              <label for="date">Date*</label>
          </div>
          <div class="col-75">
              <input type="text" class="date form-control" name="date" />
          </div>

          <script type="text/javascript">
            $('.date').datepicker({
                format: 'dd/mm/yyyy'
                });
          </script>


          <br>
          </br>

          <div class="col-20">
            <label for="type_vehicle">Type of vehicle*</label>
          </div>
          <div class="col-75">
            <select id="type_vehicle" class="form-control" name="type_vehicle">
                <option value="car">Car</option>
                <option value="motorcyle">Motorcyle</option>
                <option value="lorry">Lorry</option>
                <option value="van">Van</option>
            </select>
          </div>

          <br>
          </br>

	        <div class="col-20">
              <label for="plate_number">Plate Number*</label>
          </div>
          <div class="col-75">
              <input type="text" class="form-control" name="plate_number"/>
          </div>



          <br>
          <br>
          </br>
          </br>

          <center>
          <button type="submit" class="btn btn-success">Register</button>
          </center>

      </form>
  </div>
</div>
</div>
</div>
@endsection

resources/views/visitorrs/displayCheckIn.blade.php
@extends('layouts.app')

@section('content')
<head>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/css/bootstrap-datepicker.css" rel="stylesheet">
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/js/bootstrap-datepicker.js"></script>
</head>
<style>
.col-20 {
float: left;
width: 20%;
margin-top: 6px;
}

.col-75 {
float: left;
width: 75%;
margin-top: 6px;
}
</style>

<div class="container">
<div class="row">
 <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3"><center>Visitor</center></h1>
  <div>

      <form method="post" action="/visitorCheckedIn">
          @csrf
          <input name=token value="{{ $checkin->token }}" hidden>
          <div class="col-20">
              <label for="full_name">Visitor Name:</label>
          </div>
          <div class="col-75">
              {{ $visitors->full_name}}
          </div>

          <br>
          </br>

          <div class="col-20">
              <label for="ic_no">IC Number:</label>
          </div>
          <div class="col-75">
              {{ $visitors->ic_no}}
          </div>

          <br>
          </br>

          <div class="col-20">
              <label for="email">Email:</label>
          </div>
          <div class="col-75">
              {{ $visitors->email}}
          </div>

          <br>
          </br>

          <div class="col-20">
              <label for="phone_number">Phone Number:</label>
          </div>
          <div class="col-75">
          </div>
            {{ $visitors->phone_number}}
          <br>
          </br>

          <div class="col-20">
              <label for="date">Date:</label>
          </div>
          <div class="col-75">
              {{ $visitors->date}}
          </div>

          <br>
          </br>

          <div class="col-20">
            <label for="type_vehicle">Type of vehicle:</label>
          </div>
          <div class="col-75">
              {{ $visitors->type_vehicle}}
          </div>

          <br>
          </br>

	        <div class="col-20">
              <label for="plate_number">Plate Number:</label>
          </div>
          <div class="col-75">
              {{ $visitors->plate_number}}
          </div>



          <br>
          <br>
          </br>
          </br>

          <center>
          <button type="submit" class="btn btn-success">Check In</button>
          </center>

      </form>
  </div>
</div>
</div>
</div>
@endsection

resources/views/visitorrs/displayCheckOut.blade.php
@extends('layouts.app')

@section('content')
<head>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/css/bootstrap-datepicker.css" rel="stylesheet">
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/js/bootstrap-datepicker.js"></script>
</head>
<style>
.col-20 {
float: left;
width: 20%;
margin-top: 6px;
}

.col-75 {
float: left;
width: 75%;
margin-top: 6px;
}
</style>

<div class="container">
<div class="row">
 <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3"><center>Visitor</center></h1>
  <div>

      <form method="post" action="/visitorCheckedOut">
          @csrf
          <input name=token value="{{ $checkout->token }}" hidden>
          <div class="col-20">
              <label for="full_name">Visitor Name:</label>
          </div>
          <div class="col-75">
              {{ $visitors->full_name}}
          </div>

          <br>
          </br>

          <div class="col-20">
              <label for="ic_no">IC Number:</label>
          </div>
          <div class="col-75">
              {{ $visitors->ic_no}}
          </div>

          <br>
          </br>

          <div class="col-20">
              <label for="email">Email:</label>
          </div>
          <div class="col-75">
              {{ $visitors->email}}
          </div>

          <br>
          </br>

          <div class="col-20">
              <label for="phone_number">Phone Number:</label>
          </div>
          <div class="col-75">
          </div>
            {{ $visitors->phone_number}}
          <br>
          </br>

          <div class="col-20">
              <label for="date">Date:</label>
          </div>
          <div class="col-75">
              {{ $visitors->date}}
          </div>

          <br>
          </br>

          <div class="col-20">
            <label for="type_vehicle">Type of vehicle:</label>
          </div>
          <div class="col-75">
              {{ $visitors->type_vehicle}}
          </div>

          <br>
          </br>

	        <div class="col-20">
              <label for="plate_number">Plate Number:</label>
          </div>
          <div class="col-75">
              {{ $visitors->plate_number}}
          </div>



          <br>
          <br>
          </br>
          </br>

          <center>
          <button type="submit" class="btn btn-success">Check Out</button>
          </center>

      </form>
  </div>
</div>
</div>
</div>
@endsection

resources/views/visitorrs/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h1 class="display-3">Update a visitor</h1>

        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        <br />
        @endif
        <form method="post" action="{{ route('visitorrs.update', $visitorr->id) }}">
            @method('PATCH')
            @csrf
            <div class="form-group">

                <label for="full_name">Full Name:</label>
                <input type="text" class="form-control" name="full_name" value={{ $visitorr->full_name }} />
            </div>

            <div class="form-group">
                <label for="ic_no">IC NO:</label>
                <input type="text" class="form-control" name="ic_no" value={{ $visitorr->ic_no }} />
            </div>

            <div class="form-group">
                <label for="email">Email:</label>
                <input type="text" class="form-control" name="email" value={{ $visitorr->email }} />
            </div>
            <div class="form-group">
                <label for="phone_number">Phone Number:</label>
                <input type="text" class="form-control" name="phone_number" value={{ $visitorr->phone_number }} />
            </div>
            <div class="form-group">
                <label for="type_vehicle">Type of vehicle:</label>
                <input type="text" class="form-control" name="type_vehicle" value={{ $visitorr->type_vehicle }} />
            </div>
            <div class="form-group">
                <label for="color">Color:</label>
                <input type="text" class="form-control" name="color" value={{ $visitorr->color }} />
            </div>
			      <div class="form-group">
                <label for="plate_number">Plate Number:</label>
                <input type="text" class="form-control" name="plate_number" value={{ $visitorr->plate_number }} />
            </div>
          


            <button type="submit" class="btn btn-primary">Update</button>
        </form>
    </div>
</div>
@endsection

resources/views/visitorrs/historyVisitor.blade.php
@extends('layouts.appAdmin3')

@section('content')
  <div class="container">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
      <div class="row">
  <div class="col-sm-12">
      <h1 class="display-3">Visitors</h1>
      <table class="table table-striped">

        <div class="col-md-5">
          <form action="/search7" method="get">
          <div class="input-group">
            <button type="submit"a href="http://localhost:8000/historyVisitor"><i class="fa fa-arrow-left" style="font-size:15px;color:black" ></i></a></button>
            <input type="search7" name="search7" class="form-control">
            <span class="input-group-prepend">
              <button type="submit" class="btn btn-primary">Search</button>
            </span>
          </div>
          </form>
        </div>

        <br>
      <thead>
          <tr>
            <td>No</td>
            <td>Full Name</td>
            <td>IC Number</td>
            <td>Email</td>
            <td>Phone Number</td>
            <td>Date</td>
            <td>Type of vehicle</td>
            <td>Plate Number</td>
            <td>Unit No</td>
            <td colspan = 2>Status</td>
          </tr>
      </thead>
      <tbody>
          @foreach($visitorrs as $visitorr)
          <tr>
              <td>{{$loop->iteration}}</td>
              <td>{{$visitorr->full_name}}</td>
              <td>{{$visitorr->ic_no}}</td>
              <td>{{$visitorr->email}}</td>
              <td>{{$visitorr->phone_number}}</td>
              <td>{{$visitorr->date}}</td>
              <td>{{$visitorr->type_vehicle}}</td>
              <td>{{$visitorr->plate_number}}</td>
              <td>{{$visitorr->unitNo}}</td>
              <td>{{$visitorr->status}}</td>
              <td>{{$visitorr->status2}}</td>

          </tr>
          @endforeach
      </tbody>
    </table>
  <div>
  </div>
  </div>
  @endsection

  <div class="col-sm-12">

    @if(session()->get('success'))
      <div class="alert alert-success">
        {{ session()->get('success') }}
      </div>
    @endif

resources/views/visitorrs/homes.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
	<div class="col-sm-12">
        <h1> Hi ! <br>
	<b>{{ Auth::user()->name }} </b> <br>
	<b>{{ Auth::user()->user_id }} </b>
	</h1>

	</div>
    </div>
</div>
@endsection

resources/views/visitorrs/index.blade.php
@extends('layouts.app')

@section('content')
  <div class="container">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
      <div class="row">
  <div class="col-sm-12">
      <h1 class="display-3">Visitors</h1>
      <table class="table table-striped">

        <div class="col-md-5">
          <form action="/search2" method="get">
          <div class="input-group">
            <button type="submit"a href="http://localhost:8000/visitorrs"><i class="fa fa-arrow-left" style="font-size:15px;color:black" ></i></a></button>
            <input type="search2" name="search2" class="form-control">
            <span class="input-group-prepend">
              <button type="submit" class="btn btn-primary">Search</button>
            </span>
          </div>
          </form>
        </div>

        <br>
      <thead>
          <tr>
            <td>No</td>
            <td>Full Name</td>
            <td>IC Number</td>
            <td>Email</td>
            <td>Phone Number</td>
            <td>Type of vehicle</td>
            <td>Date</td>
            <td>Plate Number</td>
            <td>Status</td>
            <td colspan = 2>Actions</td>
          </tr>
      </thead>
      <tbody>
          @foreach($visitorrs as $visitorr)
          <tr>
              <td>{{$loop->iteration}}</td>
              <td>{{$visitorr->full_name}}</td>
              <td>{{$visitorr->ic_no}}</td>
              <td>{{$visitorr->email}}</td>
              <td>{{$visitorr->phone_number}}</td>
              <td>{{$visitorr->type_vehicle}}</td>
              <td>{{$visitorr->date}}</td>
              <td>{{$visitorr->plate_number}}</td>
              <td>{{$visitorr->status== "CheckIn" ? 'Check In' : 'Pending'}}</td>
              <td>
                  <a href="{{ route('visitorrs.edit',$visitorr->id)}}" button class="btn btn-primary"><i class="fa fa-pencil"></i></button></a>
              </td>
              <td>
                  <form action="{{ route('visitorrs.destroy', $visitorr->id)}}" method="post">
                    @csrf
                    @method('DELETE')
                    <button class="btn btn-danger" onclick="return confirm('Are you sure to delete?')"><i class="fa fa-trash-o"></i></button>
                  </form>
              </td>
          </tr>
          @endforeach
      </tbody>
    </table>
  <div>
  </div>
  </div>
  @endsection

  <div class="col-sm-12">

    @if(session()->get('success'))
      <div class="alert alert-success">
        {{ session()->get('success') }}
      </div>
    @endif